### ISSUE TITLE
Add more functionality to profile page

### ISSUE THREAD

**Issue by SuprajaKalva** [COSC481W-2021Winter/capstone-project-film-club#106]
As a user, I want to see more features on the profile page. As a user, I want to be able to see the friends I've added and the movies I've watched so I don't have to go out of my way to find those things.

- [x] Add friend list button
- [x] Display complete history of watched movies
- [x] Enable users to edit profile picture

**Comment by nfishel48** [comment]
https://github.com/COSC481W-2021Winter/capstone-project-film-club/pull/115
