### ISSUE TITLE
Fix bugs and issues on the edit/update profile section on the profile page

### ISSUE THREAD

**Issue by SuprajaKalva** [COSC481W-2021Winter/capstone-project-film-club#117]
- [x] Fix the bug related to profile picture storage 
- [x] Clean up the CSS and design for this section 
- [x] Make sure the features of this section works well with the rest of the other divs in the page such as like and comment

**Comment by sjiang1** [comment]
All the features in issue #115 work nicely with the rest of the page, and the style of the page should look pretty.

**Comment by nfishel48** [comment]
looks like nick went ahead and fixed this
