### ISSUE TITLE
Fix General CSS / Design on the web application

### ISSUE THREAD

**Issue by SuprajaKalva** [COSC481W-2021Winter/capstone-project-film-club#118]
- [ ] (1) When a user signs up for the first time, they don’t have a profile pic, redirect the profile pic to a sample profile picture for the user 
- [x] (2) Need to fix the CSS for the movie page on Firefox
- [x] (3) Change the name from add friend to follow
- [x] (4) Change the links in Quick Links (add more links if needed)
- [ ] (5) Add padding to the footer in the profile page (and everywhere..?)
- [x] (6) Add a div on the profile page when it is empty
- [x] (7) Fix the background picture for the background video… (or research how to add it to AWS…)
- [x] (8) CSS for the back button on the about us page
- [x] (9) Add a back button on the registration page
- [ ] (10) Make sure the footer is attached to the bottom of the page
- [ ] (11) Add a footer to the home screen?
- [x] (12) Change the name on the tab (change title) to Film Club instead of the user's name on their homepage once they are logged in

**Comment by sjiang1** [comment]
Please update the issue once you split the job into four parts.

**Comment by SuprajaKalva** [comment]
Supraja

- 2, 4, 7, 12

David

- 8, 9

Andrew

- 1, 5, 10, 11

Nick

- 3, 6
