### ISSUE TITLE
Ability to edit personal information on profile

### ISSUE THREAD

**Issue by NickJGG** [COSC481W-2021Winter/capstone-project-film-club#38]
- [x] Users register with all the correct information (First and last name, profile picture)
- [x] All public information is displayed on the profile
- [x] Users can edit their information in a form on the profile page

**Comment by SuprajaKalva** [comment]
Need to fix the bugs when the user uploads a picture, back-end works fine

**Comment by SuprajaKalva** [comment]
Deleted date of birth as a field to protect users' privacy

**Comment by SuprajaKalva** [comment]
Nick helped fix the bugs 👍
