### ISSUE TITLE
requirements.txt is broken

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2021Winter/capstone-project-film-club#60]
In the requirements.txt:
> Pillow-8.1.2

should be 

> Pillow==8.1.2

**Comment by SuprajaKalva** [comment]
I fixed this in my branch. It will be fixed once it merges in. Thank you!

**Comment by sjiang1** [comment]
> I fixed this in my branch. It will be fixed once it merges in. Thank you!

Great! Once you do the pull request merge, you can mark this issue fixed.

**Comment by SuprajaKalva** [comment]
Fixed the requirements.txt
