### ISSUE TITLE
Multiple Browser/Support

### ISSUE THREAD

**Issue by SuprajaKalva** [COSC481W-2021Winter/capstone-project-film-club#93]
As a user, I want to be able to see the website information cleanly on multiple browsers. 

- [ ] Fix to allow multiple browser support

**Comment by sjiang1** [comment]
Testing multiple browsers (such as firefox, chrome) to make sure the elements of the website show correctly on those browsers.

**Comment by SuprajaKalva** [comment]
Tested and fixed landing and register pages in firefox and chrome. Other pages seem to be working fine as well.
